### ISSUE TITLE
php-yaml extension has to be installed

### ISSUE THREAD

**Issue by CharlesNepote** [sylvainhalle/FantasticWindmill#3]
1. At least I suggest to write it clearly in the documentation.
   The installation is not so hard but has to be done. See: https://code.google.com/p/php-yaml/wiki/InstallingWithPecl
   Be careful on Debian/Ubuntu /etc/php5/cli/php.ini has to be complete during php-yaml installation.
2. Some hosting services do not allow to install php extentions. It would be very interesting include in FW a pure yaml php implementation such as Symphony's one: http://symfony.com/components/Yaml

**Comment by sylvainhalle** [comment]
Spyc seems to be the simplest choice: https://github.com/mustangostang/spyc
